displayName: plugin demo
type: middleware

import: github.com/dragosnutu/traefik-plugin

summary: '[Demo] Add Request Header'

testData:
  JwtField: sub
  JwtValues:
    - '1234567890'
  Redirect: 'http://localhost/redirected'