[entryPoints]
[entryPoints.web]
address = ":80"

[providers]
[providers.docker]
watch = true

[api]
insecure = true

[log]
level = "DEBUG"

[pilot]
token = "6ebd0271-f69d-4fc5-bb74-26e2d3a4dc1d"

[experimental.plugins]

[experimental.plugins.block]
modulename = "github.com/traefik/plugin-blockpath"
version = "v0.2.1"

[experimental.plugins.rewrite]
modulename = "github.com/traefik/plugin-rewritebody"
version = "v0.3.1"

#[experimental.plugins.myplugin]
#modulename = "github.com/dragosnutu/traefik-plugin"
#version = "v0.0.2"

[experimental.devPlugin]
goPath="/development"
moduleName="github.com/dragosnutu/traefik-plugin"